### ISSUE TITLE
Structures contain blocks from Quark Oddities

### ISSUE THREAD

**Issue by MuteTiefling** [craisinlord/IDAS#13]
Perhaps just a misunderstanding on my part, but some structures use blocks from Quark Odditites in the design. This isn't a listed dependency, however. 

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/324

Example found in castles: 
![image](https://user-images.githubusercontent.com/9543430/235509737-f5d25f1b-d592-4ddb-9414-0d59da3a118a.png)

Would it be possible to have these get replaced automatically if Oddities is not enabled?

**Comment by NielsPilgaard** [comment]
In addition to this, it would be very helpful for us if all chests spawned in Integrated Structures were based on loot tables, so we can modify/unify stuff in them :)

Edit: @theboo explained that the chests are most likely already loot table based, so please ignore this comment 😅 
https://github.com/EnigmaticaModpacks/Enigmatica9/issues/323#issuecomment-1532063974

**Comment by craisinlord** [comment]
This was fixed in 1.6.6 and 1.7.4

**Comment by MuteTiefling** [comment]
We're still seeing these Quark Storage Crates in 1.7.6. Was there something we needed to do to disable them, or should it be automatic?
